spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:

logging:
  level:
    com.partick.springcloudcourse.server.mapper: trace

mybatis:
  mapper-locations: classpath:/mapper/*.xml
