spring:
  application:
    name: gateway
  #路由转发
  cloud:
    gateway:
      routes:
        - id: system
          uri: http://127.0.0.1:9111
          predicates:
            - Path=/system/**
        - id: business
          uri: http://127.0.0.1:9112
          predicates:
            - Path=/business/**
server:
  port: 9000
eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/
