spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
server:
  port: 9111
  servlet:
    context-path: /system
eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka/